### ISSUE TITLE
isConnected test fails on unbranded micro OLED display

### ISSUE THREAD

**Issue by PaulZC** [sparkfun/SparkFun_Micro_OLED_Arduino_Library#26]
Example6_DrawIcon uses the standard ```isConnected``` test to discover a display with address 0x3D or 0x3C.
The _**unbranded**_ OLED display I have fails this test:

![image](https://user-images.githubusercontent.com/5690545/101791576-9a02a900-3afb-11eb-93c9-915454b2fb17.png)

If the SparkFun displays pass this test, then please close with extreme prejudice!
Paul

**Comment by nseidle** [comment]
[Qwiic OLED](https://www.sparkfun.com/products/14532) happily acks at 0x3D (default address). 

![image](https://user-images.githubusercontent.com/117102/101816523-5b122a80-3ade-11eb-937f-478b45c95bfd.png)
Don't mind the 0x42 u-blox GNSS and 0x36 MAX17048 fuel gauge, I tested on the ESP32 [RTK Surveyor](https://www.sparkfun.com/products/17369) that has these built in.

What address does your unbranded display ack to?

**Comment by PaulZC** [comment]
It's really very strange... It defaults to address 0x3C and ACKs OK when I write data to it:
![image](https://user-images.githubusercontent.com/5690545/101919492-8a01cc80-3bc2-11eb-98ac-cdf8551ca47b.png)

But doesn't respond to ```isConnected``` either way round:
![image](https://user-images.githubusercontent.com/5690545/101919754-d816d000-3bc2-11eb-8e63-8645e7307ad9.png)

![image](https://user-images.githubusercontent.com/5690545/101920010-2d52e180-3bc3-11eb-9532-364da7f1b188.png)

I suggest we don't lose any sleep over this as it is an _unbranded_ display, but maybe we should leave this issue open (and make it sticky?) just in case any users have the same issue?

**Comment by lewispg228** [comment]
Hey Paul and Nathan,
Not sure if this is helpful, but this reminds me of an issue I ran into with the cryptographic IC I worked on a while ago. It required a "wake" command (which I think is actually kind of an old standard to wake up an entire I2C bus?). It basically just means holding the SDA line low for a specific amount of time. I ended up having to do something different than our usual isConnected(). Maybe this unbranded OLED would like to see a wake command first?

[Here](https://github.com/sparkfun/SparkFun_ATECCX08a_Arduino_Library/blob/master/src/SparkFun_ATECCX08a_Arduino_Library.cpp#L51) is where I implemented it in the ATECCX08a library. 

From the ATECC508A datasheet: 

"
The Wake condition requires that either the system processor manually drives the SDA pin low for tWLO,
or a data byte of 0x00 be transmitted at a clock rate sufficiently slow so that SDA is low for a minimum
period of tWLO

"

For the ATECC508a the required time was 60uS, so writing 0x00 at 100kHz was sufficient.

Hope this is helpful. Might be worth a shot?

**Comment by PaulZC** [comment]
Thanks Pete - I'll give it a try!
All the best,
Paul

**Comment by PaulZC** [comment]
So, pulling SDA low didn't seem to do the trick. But that got me thinking... And if I give the display a manual reset before trying ```isConnected``` then it does work! Cheers Pete - you're my inspiration! ;-D

@nseidle: should we update the example? I'm not seeing any downside?

![image](https://user-images.githubusercontent.com/5690545/101927751-b91d3b80-3bcc-11eb-90b1-6084bce7938a.png)

**Comment by nseidle** [comment]
Sounds good to me!

**Comment by PaulZC** [comment]
Done. The [new version](https://github.com/sparkfun/SparkFun_Micro_OLED_Arduino_Library/commit/a36b432fd47c479646815657a4cd0dd3e9427643#diff-0cc0f1557ae9035f8ce4c65683e5abb861dfeaa7c575377c1c24df9daca24f85R83-R89) is in the release_candidate branch for now...
And that makes it beer-o'-clock!
Closing...
